alias gss="git status --short"
alias gcmsg="git commit -m"
alias gcn!="git commit --amend --no-edit"
alias ga="git add"
alias gaa="git add ."
alias gd="git diff"
alias grb="git rebase"
alias gf="git fetch"
alias gl="git pull"
alias gpr="git pull --rebase"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias grhs="git reset --soft"
alias grhh="git reset --hard"
alias gcb="git checkout -b"
alias gco="git checkout"
alias grs="git restore"
alias gsta="git stash add"
alias gstd="git stash drop"
alias gstl="git stash list"
alias grm="git rm"
alias grmc="git rm --cached"
alias glol="git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\""
alias glola="git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\" --all"
